version: "3.9"

services:
  ddb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./data:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath . -cors '*'"
