name: OIDC CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CD_ROLE_ARN }}
          role-session-name: ${{ github.sha }}
          aws-region: eu-central-1
      - name: Create Outputs Directory
        run: mkdir -p terraform/outputs

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Build Go
        run: make build_go

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Node
        run: make build_node

      - name: Run Terraform
        # Get "env_vars" variable from github secrets and pass it to terraform. The variable name on github secrets should be "ENV_FILE"
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var-env_vars="${{ secrets.ENV_FILE }}"
